### ISSUE TITLE
scales: attempt to call a nil value (field 'amp')

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/we#24]
I get the following error when trying to open the scales demo on the buildroot image
```
Dec 21 19:06:31 norns ws-wrapper[129]: # script load: /root/dust/code/we/demos/scales.lua
Dec 21 19:06:31 norns ws-wrapper[129]: # cleanup
Dec 21 19:06:31 norns ws-wrapper[129]: # script clear
Dec 21 19:06:31 norns ws-wrapper[129]: pset >> write: /root/dust/data/system.pset
Dec 21 19:06:31 norns ws-wrapper[129]: # script run
Dec 21 19:06:31 norns ws-wrapper[129]: loading engine: PolyPerc
Dec 21 19:06:31 norns ws-wrapper[129]: Engine.register_commands; count: 0
Dec 21 19:06:31 norns ws-wrapper[129]: ___ engine commands ___
Dec 21 19:06:31 norns ws-wrapper[129]: ___ polls ___
Dec 21 19:06:31 norns ws-wrapper[129]: amp_in_l
Dec 21 19:06:31 norns ws-wrapper[129]: amp_in_r
Dec 21 19:06:31 norns ws-wrapper[129]: amp_out_l
Dec 21 19:06:31 norns ws-wrapper[129]: amp_out_r
Dec 21 19:06:31 norns ws-wrapper[129]: cpu_avg
Dec 21 19:06:31 norns ws-wrapper[129]: cpu_peak
Dec 21 19:06:31 norns ws-wrapper[129]: pitch_in_l
Dec 21 19:06:31 norns ws-wrapper[129]: pitch_in_r
Dec 21 19:06:31 norns ws-wrapper[129]: # script init
Dec 21 19:06:31 norns ws-wrapper[129]: ### SCRIPT ERROR: init
Dec 21 19:06:31 norns ws-wrapper[129]: /root/dust/code/we/demos/scales.lua:110: attempt to call a nil value (field 'amp')
Dec 21 19:06:31 norns ws-wrapper[129]: stack traceback:
Dec 21 19:06:31 norns ws-wrapper[129]:         /usr/share/norns/lua/core/norns.lua:215: in field 'amp'
Dec 21 19:06:31 norns ws-wrapper[129]:         /root/dust/code/we/demos/scales.lua:110: in function 'init'
Dec 21 19:06:31 norns ws-wrapper[129]:         /usr/share/norns/lua/core/script.lua:77: in function 'core/script.init'
Dec 21 19:06:31 norns ws-wrapper[129]:         [C]: in function 'xpcall'
Dec 21 19:06:31 norns ws-wrapper[129]:         /usr/share/norns/lua/core/norns.lua:216: in field 'try'
Dec 21 19:06:31 norns ws-wrapper[129]:         /usr/share/norns/lua/core/engine.lua:89: in function </usr/share/norns/lua/core/engine.lua:88>
Dec 21 19:06:31 norns ws-wrapper[129]: >> reading PMAP /root/dust/data/we/demos/scales/scales.pmap
```

Points to this line

https://github.com/monome/we/blob/master/demos/scales.lua#L110

**Comment by simonvanderveldt** [comment]
I get slightly further on the norns 2.2.2. stack (as in I now see the UI of scales) but I still get the same error and no sound.

**Comment by tehn** [comment]
thanks for the heads up, can work on this later today

**Comment by tehn** [comment]
can't replicate.

something with buildroot. the problem is actually further up:

> Dec 21 19:06:31 norns ws-wrapper[129]: loading engine: PolyPerc
> Dec 21 19:06:31 norns ws-wrapper[129]: Engine.register_commands; count: 0

that 0 is no good

**Comment by simonvanderveldt** [comment]
@tehn Thanks, that was enough of a hint. Seems like I'm missing PolyPerc. Just did a quick search an it seems it's still included in the dust repo (https://github.com/monome/dust/blob/35158b89cbd82aa6f9a886deb6e1b220ec7a60ef/lib/sc/Engine_PolyPerc.sc). I thought we no longer used the things from dust so the only thing I'm including are the audio files from the tgz on digitalocean.

Where should these engine files live? If they are part of the base norns stack maybe we should move them to the norns repo?

**Comment by tehn** [comment]
you're correct, we don't use `dust`

it's in https://github.com/tehn/awake and we should probably put it (along with polysub and simpletest) in the norns repo

yes, we should investigate the missing engine error message

**Comment by simonvanderveldt** [comment]
Follow-up issues
https://github.com/monome/norns/issues/949
https://github.com/monome/norns/issues/948
